### ISSUE TITLE
签到数据库错误后续

### ISSUE THREAD

**Issue by rumosky** [BennyThink/GreenGrapes2#8]
根据上次给的debug，我得到了下面的错误
```
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x98' for column 'text' at row 1
Typecho_Db_Query_Exception: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x98' for column 'text' at row 1 in /www/wwwroot/rumosky.net/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /www/wwwroot/rumosky.net/var/Typecho/Db.php(354): Typecho_Db_Adapter_Pdo->query('INSERT INTO typ...', Object(PDO), 2, 'INSERT')
#1 /www/wwwroot/rumosky.net/var/Widget/Abstract/Comments.php(189): Typecho_Db->query(Object(Typecho_Db_Query))
#2 /www/wwwroot/rumosky.net/var/Widget/Feedback.php(140): Widget_Abstract_Comments->insert(Array)
#3 /www/wwwroot/rumosky.net/var/Widget/Feedback.php(336): Widget_Feedback->comment()
#4 /www/wwwroot/rumosky.net/var/Typecho/Router.php(138): Widget_Feedback->action()
#5 /www/wwwroot/rumosky.net/index.php(23): Typecho_Router::dispatch()
#6 {main}
```
这次跟上次不一样，我更新了你的模板，这次点击签到之后网页自动刷新，刷新完成之后没有显示数据库请求错误，也没有在评论区显示签到数据，就什么都没做。

**Comment by BennyThink** [comment]
General error: 1366 Incorrect string value: '\xF0\x9F\x98\x98'     似乎是utf8mb4 的事
